import express from 'express';
import routes from './http/routes.mjs';
import handleError from './http/errors.mjs';
const application = express();
application.disable('x-powered-by');
application.use(express.json({ limit: '16kb' }));
application.get('/', (request, response) => response.json({ application: 'AddressBook API', version: '1.0.0', endpoints: ['POST /contacts', 'GET /contacts', 'GET /contacts/:id', 'PUT /contacts/:id', 'DELETE /contacts/:id'] }));
application.use('/contacts', routes);
application.use((request, response) => response.status(404).json({ success: false, message: 'Endpoint not found' }));
application.use(handleError);
export default application;
